Git homework
akarev0/common pull request #1
Opened 2019-09-23 18:04 UTC by akarev0

2019-09-26 09:22 UTC, alchemixXx requested changes

2019-09-26 09:22 UTC, alchemixXx commented on git/homework.py
redundant statement "if". Operator "==" will already return True or False.
Make the refactoring.

2019-09-26 09:22 UTC, alchemixXx commented on git/homework.py
The same that in #1.

2019-09-26 09:22 UTC, alchemixXx commented on git/homework.py
The same that in #1.

2019-09-26 09:22 UTC, alchemixXx commented on git/homework.py
The same that in #1 (but with "in" against "==").

2019-09-26 09:22 UTC, alchemixXx commented on git/homework.py
could combine lines 141 and 142. You don't need to create separate variable for list compr.

2019-09-27 12:06 UTC, yuriimchg approved these changes
все дуже круто
сортування просто бомба
але не переписуй більше тести, будь ласка)

2019-09-27 12:06 UTC, yuriimchg commented on git/homework.py
> +            continue
+ за `continue`

якщо матимеш час / бажання / натхнення, можна це переробити через list compregensions так, як це в наступному завданні

2019-09-27 12:06 UTC, yuriimchg commented on git/homework.py
> +    return [i for i in data if i >= 0]
:+1: :fire:

2019-09-27 12:06 UTC, yuriimchg commented on git/homework.py
> +        alphabet_value[letter] = ascii_lowercase.index(letter) + 1
логіка виглядає досить цікаво
але наступного разу, будь ласка, не переписуй юніттести для того, щоб твій код працював :wink: 
навіть, якщо в умові помилка

2019-09-27 12:06 UTC, yuriimchg commented on git/homework.py
> +        return simple_sort(less) + [middle] + simple_sort(greater)
+++ за сортування не бульбашкою

2019-10-07 16:49 UTC, merged