Oop homework
akarev0/common pull request #10
Opened 2019-10-19 16:33 UTC by akarev0

2019-10-19 20:38 UTC, yuriimchg requested changes

2019-10-19 20:38 UTC, yuriimchg commented on oop/homework.py
> +        self._increase_saturation_level(food_inc.get(product))
до речі
ще звернув увагу на одну штуку
якщо кіт з'їсть їжу, якої нема в словнику, то поверне TypeError
тому треба додати до dict.get() ще дефолтне значення
```suggestion
        self._increase_saturation_level(food_inc.get(product, default=0))
```

2019-10-19 20:38 UTC, yuriimchg commented on oop/homework.py
> +        food_inc = {"gazelle": 30, "rabbit": 15, "another_food": 0}
тут аналогічно

2019-10-19 20:38 UTC, yuriimchg commented on oop/homework.py
>              raise ValueError("Sorry we don't have such material")
в цьому методі схожа проблемка
але тут краще винести цю перевірку зразу перед обчисленням змінної  `result`

2019-10-20 06:28 UTC, akarev0 commented on oop/homework.py
> +        self._increase_saturation_level(food_inc.get(product))
https://stackoverflow.com/questions/24463202/typeerror-get-takes-no-keyword-arguments

2019-10-20 07:30 UTC, yuriimchg approved these changes
:+1:

2019-10-20 07:30 UTC, yuriimchg commented on oop/homework.py
> +        result = self.door_square() * materials.get(material_value, 0)
тут вже не обов'язково дефолтне значення, бо будь-які матеріали, крім дерева й металу, викличуть ValueError

2019-10-20 07:45 UTC, merged