Advanced flask
akarev0/common pull request #13
Opened 2019-11-02 08:25 UTC by akarev0

2019-11-08 21:30 UTC, yuriimchg requested changes
привіт
переглянув дз
виглядає круто, але ~~я не буду їсти вівсянку за 8 мільйонів баксів~~ є зауваження:

* немає функціоналу, щоб додати супермаркети
* не можу додати новий продукт (немає повідомлення про те, що він додався і він не відображається в доданих ) і не вискакує повідомлення про те, що він додався / не додався
* дуже бракує підписів для нових продуктів. Я як користувач не знаю, куди вводити ціну, назву, опис і тд
* No newline at the end of file
* лінтер трохи свариться
* нагадую про type hints
* нагадую про можливість фільтрувати продукти / супермаркети

2019-11-08 21:30 UTC, yuriimchg commented on advanced_flask/routes/products/template/all_products.html
> +        <li>
думаю, цю штуку можна зобразити циклом

2019-11-08 21:30 UTC, yuriimchg commented on advanced_flask/routes/products/utils.py
> +        return json.load(file)
не використовуй `file` як змінну - легко плутається з типом file

2019-11-08 21:30 UTC, yuriimchg commented on advanced_flask/routes/products/utils.py
> +            data = json.load(file)
тут також

2019-11-11 22:02 UTC, yuriimchg reviewed
:checkered_flag: лінтер все ще свариться
:checkered_flag: можу генерувати продукти з від'ємною ціною
![image](https://user-images.githubusercontent.com/33547678/68624096-c1450c00-04de-11ea-814c-3c35f5542d8c.png)
:checkered_flag: #kyivnotkiev
:checkered_flag: нагадую про type hints і можливість фільтрувати їжу / магазини

2019-11-11 22:02 UTC, yuriimchg commented on advanced_flask/routes/products/template/all_products.html
> +{% endblock %}
No newline

2019-11-15 14:07 UTC, dimigor requested changes

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/routes/products/products.py
> +            add_products_data('routes/products/products.json', all_products)
hardcoded path to file. Make it as constant

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/routes/products/products.py
> +
too much blank lines

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/routes/products/template/price_filter.html
> +{% endblock %}
endline

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/routes/products/utils.py
> +    with open("routes/products/products.json") as product_data:
hardcoded path

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/routes/supermarkets/utils.py
> +        return json.load(file)
do not use python reserved words like `file`

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/routes/supermarkets/utils.py
> +        return json.load(file)
Also, catch possible errros like `File not found` and reruen empty data if you catch

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/routes/supermarkets/utils.py
> +        return str(max([int(item.get('id')) for item in data]) + 1)
here you return str, and bellow you returned int. Always return same type

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/templates/home.html
> +
too much blank lines. You need to leave only one empty line at the bottom of every file

2019-11-15 14:07 UTC, dimigor commented on advanced_flask/templates/error_page.html
> +</html>
endline

2019-11-15 14:07 UTC, dimigor commented on flask_lesson_intro/utils.py
> +        return json.load(file)
Catch possible exceptions

2019-11-16 13:05 UTC, dimigor approved these changes

2019-11-16 14:47 UTC, merged