init normal branch
akarev0/common pull request #16
Opened 2019-11-10 11:28 UTC by akarev0

2019-11-23 01:41 UTC, yuriimchg requested changes
привіт

переглянув завдання
виглядає досить непогано, але є трохи зауважень. Я залишив зауваження до Rooms, але для інших сутностей вони аналогічні

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/config.py
> +        return Config
це можна передати через словник. `Else` - як альтернативний вибір в методі `dict.get()`

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/main.py
> +    return current_app.config['SECRET_KEY']
залишати пароль на домашній сторінці не дуже безпечно :wink:

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/main.py
> +    app.run(debug=True)
параметр з дебагом бажано винести в сетап конфігів, бо його ок використовувати в тестових середовищах, але не ок на стейджі/проді

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                        return room
ця штука не спрацювала

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        data = json.loads(request.data)
127.0.0.1:5000/rooms
якщо метод POST повертає помилку, добре б загорнути її в статус 400

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                    room.price = data.get('value')
цей код так і просить загорнути його в словник)

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                    room.price = data.get('value')
ну і воно повертає `Successfully updated` навіть, якщо нічого не апдейтить

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                rooms.remove(room)
цей кусок гарніше виглядатиме як ліст компрехеншн

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                rooms.remove(room)
+ повідомлення, яке виводиться, не фільтрує видалення кімнат, яких нема

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        data = json.loads(request.data)
і мені впринципі не вдалося додати новий запис

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        data = json.loads(request.data)
![image](https://user-images.githubusercontent.com/33547678/69470925-ec631180-0da2-11ea-8729-e88fa51516a3.png)

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/structure.py
> +}
:no_entry_sign:

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/structure.py
> +    "number": fields.Integer,
потрібне обмеження на унікальну кімнату (і значення > 0)

2019-11-23 01:41 UTC, yuriimchg commented on Flask_restful_Api/rooms/structure.py
> +    "price": fields.Integer
потрібно обмеження на додатню ціну

2019-11-23 14:37 UTC, akarev0 commented on Flask_restful_Api/rooms/rooms.py
> +                        return room
http://127.0.0.1:5000/rooms/422 - в цьому запиті просто треба передати номер кімнати

2019-11-23 15:11 UTC, akarev0 commented on Flask_restful_Api/rooms/rooms.py
> +        data = json.loads(request.data)
ти не так передаєш)

2019-11-24 21:29 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                        return room
все ок, дякую

2019-11-27 21:08 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        data = json.loads(request.data)
:man_facepalming:

2019-11-27 21:25 UTC, yuriimchg requested changes
GET 127.0.0.1:5000/rooms :ok: 
GET 127.0.0.1:5000/rooms.105 :ok: 
GET 127.0.0.1:5000/rooms/42 :no_good_man:  - має повертатися 404 з повідомленням, що такої кімнати немає.
GET 127.0.0.1:5000/rooms/weird_endpoint - :no_good_man: - має повертатися 404 з повідомленням, що такої лінки немає  або перекидати кудись чи щось таке. Старайся уникати 501 помилки.

* Номер кімнати має бути унікальним (мені вдалося створити дві кімнати з однаковим номером). Згадай дз з будинком і стінами, коли вискакувала помилка при створенні п'ятої стіни - потрібно викидати схожу помилку, коли користувач намагається створити кімнату з існуючим номером.

* Номер кімнати / ціна не можуть бути від'ємними. Потрібно обмеження на те, щоб вони були додатніми.

![image](https://user-images.githubusercontent.com/33547678/69759058-d1f5b300-1169-11ea-8e2d-47456bb8d152.png)

2019-11-27 21:25 UTC, yuriimchg commented on Flask_restful_Api/stuff/structure.py
> +}
:no_entry_sign:

2019-11-27 21:25 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                    if room.status == args.get('filter'):
не зовсім розумію, як це працює

2019-11-27 21:25 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +                    if room.status == args.get('filter'):
в ідеалі мало би бути щось схоже на https://url_base/rooms?status=closed

2019-11-27 21:25 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        data = request.args
PATCH `127.0.0.1:5000/rooms/910`
AttributeError: 'dict' object has no attribute 'number'

2019-11-27 21:25 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        [rooms.remove(room) for room in rooms if room.number == room_number]
та сама штука, що і в PATCH
AttributeError: 'dict' object has no attribute 'number'

2019-11-27 21:25 UTC, yuriimchg commented on Flask_restful_Api/rooms/structure.py
> +    "number": fields.Integer,
чому б не спробувати `fields.Integer` if `fields.Integer` > 0 else raise SomeError?

2019-11-27 21:25 UTC, yuriimchg commented on Flask_restful_Api/rooms/structure.py
> +    "number": fields.Integer,
я не впевнений, що спрацює, але це виглядає простим рішенням)

2019-11-30 08:47 UTC, akarev0 commented on Flask_restful_Api/rooms/rooms.py
> +        [rooms.remove(room) for room in rooms if room.number == room_number]
DELETE http://127.0.0.1:5000/rooms/311
в мене по отакому запиту видаляє

2019-11-30 08:50 UTC, akarev0 commented on Flask_restful_Api/rooms/rooms.py
> +        data = request.args
PATCH http://127.0.0.1:5000/rooms/105?level=second&status=closed&price=150
запрос просто пишу в роуті а не окремим json файлом передаю, отак працює

2019-11-30 09:14 UTC, akarev0 commented on Flask_restful_Api/rooms/rooms.py
> +                    if room.status == args.get('filter'):
fixed

2019-12-02 21:48 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        data = request.args
![image](https://user-images.githubusercontent.com/33547678/69998067-32b42f80-155e-11ea-8b57-57d89512a4fa.png)

2019-12-03 23:05 UTC, yuriimchg requested changes
глянув знову
виглядає значно краще, але є ще деякі зауваження
зато схоже, ніби це вже остаточний список зауважень)

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +            if args.get('filter'):
ця штука змушує шукати фільтрацію лише тоді, коли заданий номер кімнати. Так не має бути.

Зверни увагу на URL:
![image](https://user-images.githubusercontent.com/33547678/70095142-b0df0780-162c-11ea-9e1d-947707b10876.png)
![image](https://user-images.githubusercontent.com/33547678/70095173-c3594100-162c-11ea-954f-6f2bf4ef47a3.png)

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        if str(data.get('number')) in [str(room.number) for room in rooms]:
те, що треба

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        if data.get('price') >= 0:
тільки добре, щоб ціна була все ж більша за нуль

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        raise ValueError("Price cant be negative")
тут краще не ValueError, а шось таке:
https://stackoverflow.com/a/57665610/8995868

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        raise ValueError("Price cant be negative")
бо ValueError поверне 500 респонс, який виглядає не дуже інформативно:
![image](https://user-images.githubusercontent.com/33547678/70095790-46c76200-162e-11ea-9941-3d921b22036c.png)

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        [rooms.remove(room) for room in rooms if str(room.number) == room_number]
непогано було би вивести повідомлення про те, що кімната видалена або її не існує

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/rooms/rooms.py
> +        [rooms.remove(room) for room in rooms if str(room.number) == room_number]
![image](https://user-images.githubusercontent.com/33547678/70095921-9017b180-162e-11ea-8beb-06e7c3bc1ec8.png)
бо така відповідь отримується у всіх випадках

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/stuff/resource.py
> +staff = [Staff("James", "MR229561", "Director", 15000), Staff("Lars", "MR223561", "Manager", 13000),
одне з полів будь-якого запису має бути ідентичним. В даному випадку це мав би бути номер паспорта

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/stuff/staff.py
> +                person.salary = data.get('salary') or person.salary
![image](https://user-images.githubusercontent.com/33547678/70096685-4cbe4280-1630-11ea-88bd-a948389b4992.png)
немає ніякої відповіді - невідомо, чи змінився запис, чи ні

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/stuff/staff.py
> +        [staff.remove(person) for person in staff if person.name == person_name]
те саме

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/stuff/staff.py
> +                person.salary = data.get('salary') or person.salary
також мені вдалося поміняти `salary` на значення, яке не конвертується в float. Всі наступні GET запити відвалюються з 500 респонсом:
```
flask_restful.fields.MarshallingException: invalid literal for int() with base 10:
```

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/stuff/staff.py
> +                person.salary = data.get('salary') or person.salary
це обов'язково потрібно змінити на перевірку, чи є число числом на етапі PATCH методу

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/stuff/staff.py
> +        [staff.remove(person) for person in staff if person.name == person_name]
![image](https://user-images.githubusercontent.com/33547678/70096952-ec7bd080-1630-11ea-9383-4ddb42f741e7.png)

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/resource.py
> +           Tenants("Stasik", "MN12312", 17, "male", "", 420), Tenants("akarev0", "MM12129", 18, "male", "", 311)]
:no_entry_sign:

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/resource.py
> +           Tenants("Stasik", "MN12312", 17, "male", "", 420), Tenants("akarev0", "MM12129", 18, "male", "", 311)]
в прикладах не відображається Passport_id

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/resource.py
> +           Tenants("Stasik", "MN12312", 17, "male", "", 420), Tenants("akarev0", "MM12129", 18, "male", "", 311)]
хоча це поле мало би бути ідентифікатором

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/resource.py
> +           Tenants("Stasik", "MN12312", 17, "male", "", 420), Tenants("akarev0", "MM12129", 18, "male", "", 311)]
![image](https://user-images.githubusercontent.com/33547678/70097276-a8d59680-1631-11ea-8e55-814ac2be3548.png)

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/resource.py
> +           Tenants("Stasik", "MN12312", 17, "male", "", 420), Tenants("akarev0", "MM12129", 18, "male", "", 311)]
схоже, його треба додати в tenants_structure

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/tenants.py
> +                tenant.passport_id = data.get('passport_id') or tenant.passport_id
треба перевірку, чи passport_id унікальний

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/tenants.py
> +                break
потрібно додати повідомлення про результат

2019-12-03 23:05 UTC, yuriimchg commented on Flask_restful_Api/tenants/tenants.py
> +        [tenants.remove(tenant) for tenant in tenants if tenant.name == tenants_name]
і тут

2019-12-10 22:22 UTC, yuriimchg approved these changes
done
також на дозвіллі рекомендую глянути: https://realpython.com/python-f-strings/

2019-12-11 04:14 UTC, merged