Django_intro_homework
akarev0/common pull request #22
Opened 2020-01-11 12:31 UTC by akarev0

2020-01-18 07:45 UTC, yuriimchg requested changes
привіт
переглянув, все ок

потрібно тільки додати негативні випадки для тестів

2020-01-18 07:45 UTC, yuriimchg commented on django_homework/.gitignore
> +venv/
no newline

2020-01-18 07:45 UTC, yuriimchg commented on django_homework/homework/homework/tests.py
> +        self.assertIsNotNone(data)
Add negative case to tests when API returns data that can’t be parsed

2020-01-18 07:45 UTC, yuriimchg commented on django_homework/homework/homework/tests.py
> +        assert response.status_code == HTTPStatus.OK
ці тести, як і test_pockemon_API_response можна об'єднати в один і параметризувати по різних лінках

2020-01-24 16:43 UTC, dimigor approved these changes

2020-01-24 16:55 UTC, merged