Python functionality homework
akarev0/common pull request #3
Opened 2019-10-02 19:45 UTC by akarev0

2019-10-04 09:14 UTC, yuriimchg requested changes
привіт
завдання дуже класно зроблено

є тільки зауваження до лінії вкінці і до 2 завдання

2019-10-04 09:14 UTC, yuriimchg commented on python_functionality/homework.py
> +            yield x
python_functionality/homework.py:119:20: W292 no newline at end of file

2019-10-04 09:14 UTC, yuriimchg commented on python_functionality/homework.py
> +    for i in data:
змінні такі як i, j, k краще використовувати для даних типу **int**, по яких ми ітеруємо

наприклад:

for i in range(10):
    print(i)
тут ми ітеруємо по словниках, відповідно потрібно використати назву, яка б їх краще описала
наприклад person, profile чи щось таке

2019-10-04 09:14 UTC, yuriimchg commented on python_functionality/homework.py
> +                del i[k]
також краще не використовувати `del`
https://stackoverflow.com/questions/23331419/is-the-use-of-del-bad
можна замінити, наприклад, на dict.remove(key)

2019-10-04 09:14 UTC, yuriimchg commented on python_functionality/homework.py
> +    return [i for i in data if i.get('name') == value]
дуже гарне рішення :+1:

2019-10-04 09:14 UTC, yuriimchg commented on python_functionality/homework.py
> +    return min(data) if data else None
:+1:

2019-10-07 16:52 UTC, dimigor approved these changes

2019-10-07 16:54 UTC, merged