Tests homework
akarev0/common pull request #4
Opened 2019-10-03 18:03 UTC by akarev0

2019-10-09 20:32 UTC, yuriimchg requested changes
привіт

досить непогано, але є деякі коментарі до домашнього
_+_ добре було б додати ще декілька тестових випадків

2019-10-09 20:32 UTC, yuriimchg commented on tests/tests.py
> +#        self.assertRaises(ValueError, rect.get_radius_of_circumscribed_circle())
не залишай закоментований код - він захаращує місце

2019-10-09 20:32 UTC, yuriimchg commented on tests/tests.py
> +        self.assertRaises(ValueError, rect1.get_radius_of_inscribed_circle)
неправильний синтаксис для assertRaises
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises

2019-10-09 20:32 UTC, yuriimchg commented on tests/tests.py
> +        self.assertRaises(ValueError, rect1.get_radius_of_inscribed_circle)
також в тебе не викликається метод get_radius_of_inscribed_circle

2019-10-09 20:32 UTC, yuriimchg commented on tests/tests.py
> +        for i in range(2, 2):
цей цикл порожній 
https://docs.python.org/3/library/functions.html#func-range

також, якщо ти хочеш використовувати цикли в тестах, не забудь додати `subTests`
https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests

2019-10-09 20:32 UTC, yuriimchg commented on tests/tests.py
> +        for i in range(len(number_of_corners)):
https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests

2019-10-09 20:32 UTC, yuriimchg commented on tests/tests.py
> +        rect = Rectangle(2, 2)
якщо почав розбиратися (чи мав раніше досвід) з ООП - цей об'єкт краще створити за допомогою конструктора класів

https://docs.python.org/3/reference/datamodel.html#object.__init__

2019-10-15 17:54 UTC, yuriimchg submitted a review, later dismissed
перевірив, все ок з тестами

але не можу пропустити далі, оскільки в тебе, крім домашнього з тестів є ще три інші домашні;
прибери, будь ласка, їх з пул реквесту
тут є інструкція, як це : http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/

2019-10-15 17:54 UTC, yuriimchg commented on tests/tests.py
> +    def tearDown(self):
бажано, щоб teardown був нагорі - так легше його помітити, бо зазвичай тести до кінця ніхто не дивиться :wink:

2019-10-16 07:30 UTC, dimigor requested changes

2019-10-16 07:30 UTC, dimigor commented on tests/tests.py
> +    def setUp(self):
define setUp method at the top of class

2019-10-16 07:30 UTC, dimigor commented on tests_practice/tests.py
> +
too many blank lines

2019-10-16 07:30 UTC, dimigor commented on tests_practice/tests.py
> +
also, you need to write pytests

2019-10-18 07:53 UTC, dimigor approved these changes

2019-10-19 19:06 UTC, merged